### ISSUE TITLE
wine in Doecker

### ISSUE THREAD

**Issue by xiaozhah** [samrocketman/buildwine#3]
I have seen your question and helped me. Thanks~
I make a [Dockerfile](https://github.com/xiaozhah/WineDocker) in my Git.

If you want to rebuild wine sometime, I suggest you use Docker.

**Comment by samrocketman** [comment]
Thanks for the suggestion.  I’m familiar with Docker but at the time I created this it was not necessary.  I’ll keep it in mind next time!
